#!/bin/bash

if [[ "$SOURCE_BRANCH" = "develop" ]]; then
    # add -t flag to checkout.bash and update image dependencies
    sed -i "s|~/src/docker/checkout.bash|~/src/docker/checkout.bash -d|g; s|usdotfhwastol|usdotfhwastoldev|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:develop|g" \
        Dockerfile
elif [[ "$SOURCE_BRANCH" =~ ^feature/.*$ ]]; then
    # swap checkout branch in checkout.bash to release branch
    TAG=$(echo ${SOURCE_BRANCH} | cut -d "/" -f 2)
    sed -i "s|~/src/docker/checkout.bash|~/src/docker/checkout.bash -c|g; s|usdotfhwastol|usdotfhwastoldev|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$TAG|g" \
        Dockerfile
fi