name: CI
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: "/opt/carma/"
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/carma-base:develop
      env:
        INIT_ENV: "/home/carma/.base-image/init-env.sh"
        ROS_2_ENV: "/opt/ros/foxy/setup.bash"
        TERM: xterm
      options: "--user root"
    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        path: src/${{ github.event.repository.name }}
    - name: Checkout autoware.ai
      uses: actions/checkout@v3.3.0
      with:
        repository: usdot-fhwa-stol/autoware.ai
        path: src/autoware.ai
    - name: Checkout carma-utils
      uses: actions/checkout@v3.3.0
      with:
        repository: usdot-fhwa-stol/carma-utils
        path: src/carma-utils
    - name: Checkout carma-msgs
      uses: actions/checkout@v3.3.0
      with:
        repository: usdot-fhwa-stol/carma-msgs
        path: src/carma-msgs
    - name: Move source code
      run: mv $GITHUB_WORKSPACE/src /opt/carma/
    - name: Build
      run: |
        source "$INIT_ENV"
        source "$ROS_2_ENV"
        sed -i '/colcon build/ s/$/ --packages-up-to lightbar_driver/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
        make_with_coverage.bash -m -e /opt/carma/ -o ./coverage_reports/gcov
    - name: Run C++ Tests
      run: |
        source "$INIT_ENV"
        source "$ROS_2_ENV"
        sed -i '/colcon test/ s/$/ --packages-above lightbar_driver/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
        make_with_coverage.bash -t -e /opt/carma/ -o ./coverage_reports/gcov
    - name: Run SonarScanner
      uses: usdot-fhwa-stol/actions/sonar-scanner@main
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        working-dir: "/opt/carma/src/${{ github.event.repository.name }}"
