name: Docker Hub build

on:
  push:
    branches:
      - develop
      - master
      - "release/*"
      - sync_test_run
    tags:
      - "carma-system-*"
jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    with:
      tag_name_suffix: humble
      remove_suffix: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}